Use data folder for packages
openfisca/openfisca.org pull request #96
Opened 2022-10-13 15:04 UTC by clementbiron

2022-10-13 15:08 UTC, clementbiron commented
I have a little doubt, should we use `webAPI` or `endpoint` as metadata name?

2022-11-11 09:52 UTC, MattiSG requested changes
I love it, this is a beautiful as hoped for 😍 

There is however one problem: inconsistent usage of `webAPI`, sometimes targeting the Legislation Explorer, sometimes the interactive OpenAPI page (“swagger”), sometimes the endpoint itself. I guess that proves the point that the name is ambiguous 😄

What about the following metadata structure to replace `webAPI`:

```yaml
legislation_explorer: # URL to an interactive user interface for navigating implemented legislation, such as https://legislation.demo.openfisca.org or https://nz.openfisca.org
openapi_spec: # URL to an OpenAPI specification file, such as https://api.demo.openfisca.org/latest/spec
```

For the case of NZ, `website` and `legislation_explorer` would be the same, for example 🙂

2022-11-11 09:52 UTC, MattiSG commented on data/packages/aotearoa-new-zealand.yml
> +website: http://nz.openfisca.org/
```suggestion
website: https://nz.openfisca.org/
```

2022-11-11 09:52 UTC, MattiSG commented on data/packages/france.yml
> +source: https://github.com/lesmevesajudes/openfisca-barcelona
😉 
```suggestion
source: https://github.com/openfisca/openfisca-france
```

2022-11-11 09:52 UTC, MattiSG commented on data/packages/tunisia.yml
> +website: https://www.openfisca.tn
Their certificate is broken (poke @sandcha).
```suggestion
website: http://www.openfisca.tn
```

2022-11-11 09:52 UTC, MattiSG commented on data/packages/united-states.yml
> +  en: United States
```suggestion
  en: United States of America
```

2022-11-11 09:52 UTC, MattiSG commented on data/packages/country-template.yml
> +webAPI: https://legislation.fr.openfisca.org
😉 
```suggestion
webAPI: https://legislation.demo.openfisca.org
```

2022-11-11 09:53 UTC, MattiSG commented
I see how in the future we could add more metadata such as `package_name` to give custom pypy installation instructions or `endpoint` to automatically expose some data, but until we build a user interface for it, let's keep things lean. The OpenAPI spec is the most generic thing we can get, from there we can auto discover the endpoint 🙂

2022-11-11 09:58 UTC, MattiSG commented
Netlify builds fail because the base image is outdated. Can you handle that correction @clementbiron? 🙂 
@sandcha I have no knowledge about this process, if necessary, can you assist?

2022-11-11 10:01 UTC, MattiSG commented
Also, please make sure that the URLs are updated or removed if broken so we can close https://github.com/openfisca/openfisca.org/issues/91 🙂

2022-11-25 10:59 UTC, clementbiron commented
Good idea to replace `webAPI` by `legislation_explorer` and `openapi_spec`! I did a commit to update that.

2022-12-01 15:28 UTC, MattiSG approved these changes
🏗️ 🚀

2022-12-01 15:32 UTC, merged